<template>
    <div>
       
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id velit ut tortor pretium viverra suspendisse potenti. Est velit egestas dui id. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo integer. Imperdiet proin fermentum leo vel orci porta. Sed risus ultricies tristique nulla. Id interdum velit laoreet id donec ultrices tincidunt. Eget dolor morbi non arcu risus. Ac turpis egestas integer eget aliquet. Convallis tellus id interdum velit laoreet id donec ultrices tincidunt.

Varius sit amet mattis vulputate enim. Augue ut lectus arcu bibendum at varius. Id eu nisl nunc mi ipsum. Malesuada fames ac turpis egestas. At imperdiet dui accumsan sit amet nulla. Magnis dis parturient montes nascetur ridiculus mus mauris. Cras fermentum odio eu feugiat pretium nibh ipsum consequat nisl. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Suscipit adipiscing bibendum est ultricies integer quis auctor. Ornare lectus sit amet est placerat in egestas erat imperdiet. Iaculis nunc sed augue lacus. Bibendum ut tristique et egestas quis ipsum suspendisse. Diam volutpat commodo sed egestas egestas fringilla phasellus. Ultrices in iaculis nunc sed augue lacus viverra. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Tortor at risus viverra adipiscing at in tellus. Sapien pellentesque habitant morbi tristique. Maecenas accumsan lacus vel facilisis volutpat est velit egestas dui. Volutpat est velit egestas dui id ornare arcu.

Justo eget magna fermentum iaculis eu. Libero enim sed faucibus turpis in eu mi bibendum. Egestas tellus rutrum tellus pellentesque eu. Feugiat nibh sed pulvinar proin. Ligula ullamcorper malesuada proin libero nunc consequat. Pellentesque id nibh tortor id aliquet lectus proin. Nunc sed id semper risus in hendrerit gravida. Quam nulla porttitor massa id. Felis eget velit aliquet sagittis. Laoreet id donec ultrices tincidunt arcu non. Lectus nulla at volutpat diam ut venenatis. Adipiscing diam donec adipiscing tristique risus nec feugiat. Ridiculus mus mauris vitae ultricies leo integer malesuada. Id diam vel quam elementum pulvinar etiam non. Blandit libero volutpat sed cras ornare arcu dui vivamus.Pellentesque adipiscing commodo elit at imperdiet dui accumsan. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo nulla. Donec massa sapien faucibus et molestie. Eu scelerisque felis imperdiet proin. Congue mauris rhoncus aenean vel elit scelerisque. Et tortor consequat id porta nibh. Semper quis lectus nulla at volutpat diam. Purus in mollis nunc sed id semper risus in. Vitae nunc sed velit dignissim sodales ut. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla. Nec ultrices dui sapien eget mi proin sed libero. Urna duis convallis convallis tellus id. Orci a scelerisque purus semper. Ornare aenean euismod elementum nisi. Tellus elementum sagittis vitae et leo duis ut diam. Faucibus vitae aliquet nec ullamcorper sit. Congue nisi vitae suscipit tellus mauris a diam.

Porta nibh venenatis cras sed. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Auctor eu augue ut lectus arcu bibendum at. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Interdum velit laoreet id donec ultrices tincidunt arcu. Tincidunt lobortis feugiat vivamus at augue eget arcu. Proin nibh nisl condimentum id venenatis. Non pulvinar neque laoreet suspendisse interdum. Maecenas pharetra convallis posuere morbi leo urna molestie. Ultricies integer quis auctor elit sed vulputate mi. Sodales neque sodales ut etiam.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id velit ut tortor pretium viverra suspendisse potenti. Est velit egestas dui id. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo integer. Imperdiet proin fermentum leo vel orci porta. Sed risus ultricies tristique nulla. Id interdum velit laoreet id donec ultrices tincidunt. Eget dolor morbi non arcu risus. Ac turpis egestas integer eget aliquet. Convallis tellus id interdum velit laoreet id donec ultrices tincidunt.

Varius sit amet mattis vulputate enim. Augue ut lectus arcu bibendum at varius. Id eu nisl nunc mi ipsum. Malesuada fames ac turpis egestas. At imperdiet dui accumsan sit amet nulla. Magnis dis parturient montes nascetur ridiculus mus mauris. Cras fermentum odio eu feugiat pretium nibh ipsum consequat nisl. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Suscipit adipiscing bibendum est ultricies integer quis auctor. Ornare lectus sit amet est placerat in egestas erat imperdiet. Iaculis nunc sed augue lacus. Bibendum ut tristique et egestas quis ipsum suspendisse. Diam volutpat commodo sed egestas egestas fringilla phasellus. Ultrices in iaculis nunc sed augue lacus viverra. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Tortor at risus viverra adipiscing at in tellus. Sapien pellentesque habitant morbi tristique. Maecenas accumsan lacus vel facilisis volutpat est velit egestas dui. Volutpat est velit egestas dui id ornare arcu.

Justo eget magna fermentum iaculis eu. Libero enim sed faucibus turpis in eu mi bibendum. Egestas tellus rutrum tellus pellentesque eu. Feugiat nibh sed pulvinar proin. Ligula ullamcorper malesuada proin libero nunc consequat. Pellentesque id nibh tortor id aliquet lectus proin. Nunc sed id semper risus in hendrerit gravida. Quam nulla porttitor massa id. Felis eget velit aliquet sagittis. Laoreet id donec ultrices tincidunt arcu non. Lectus nulla at volutpat diam ut venenatis. Adipiscing diam donec adipiscing tristique risus nec feugiat. Ridiculus mus mauris vitae ultricies leo integer malesuada. Id diam vel quam elementum pulvinar etiam non. Blandit libero volutpat sed cras ornare arcu dui vivamus.Pellentesque adipiscing commodo elit at imperdiet dui accumsan. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo nulla. Donec massa sapien faucibus et molestie. Eu scelerisque felis imperdiet proin. Congue mauris rhoncus aenean vel elit scelerisque. Et tortor consequat id porta nibh. Semper quis lectus nulla at volutpat diam. Purus in mollis nunc sed id semper risus in. Vitae nunc sed velit dignissim sodales ut. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla. Nec ultrices dui sapien eget mi proin sed libero. Urna duis convallis convallis tellus id. Orci a scelerisque purus semper. Ornare aenean euismod elementum nisi. Tellus elementum sagittis vitae et leo duis ut diam. Faucibus vitae aliquet nec ullamcorper sit. Congue nisi vitae suscipit tellus mauris a diam.

Porta nibh venenatis cras sed. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Auctor eu augue ut lectus arcu bibendum at. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Interdum velit laoreet id donec ultrices tincidunt arcu. Tincidunt lobortis feugiat vivamus at augue eget arcu. Proin nibh nisl condimentum id venenatis. Non pulvinar neque laoreet suspendisse interdum. Maecenas pharetra convallis posuere morbi leo urna molestie. Ultricies integer quis auctor elit sed vulputate mi. Sodales neque sodales ut etiam.
    </div>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
    head() {
        return {
            //заголовок браузера
            title: 'Панель управления | АРМ администратора ИС Верификатор',           
        }
    },
    async beforeCreate() {             
       this.$store.commit('initializeStore');
       this.$store.commit('CHANGE_TITLE','Панель управления');           
    },  
})
</script>