import Vue from 'vue';

import BlockUI from 'primevue/blockui';
import Button from 'primevue/button';
import Card from 'primevue/card';
import Checkbox from 'primevue/checkbox';
import Column from 'primevue/column';
import DataTable from 'primevue/datatable';
import DataView from 'primevue/dataview';
import Dialog from 'primevue/dialog';
import Dropdown from 'primevue/dropdown';
import InputMask from 'primevue/inputmask';
import InputNumber from 'primevue/inputnumber';
import InputText from 'primevue/inputtext';
import Listbox from 'primevue/listbox';
import Message from 'primevue/message';
import Panel from 'primevue/panel';
import Password from 'primevue/password';
import ProgressBar from 'primevue/progressbar';
import RadioButton from 'primevue/radiobutton';
import Textarea from 'primevue/textarea';
import Toolbar from 'primevue/toolbar';

Vue.component('BlockUI', BlockUI);
Vue.component('Button', Button);
Vue.component('Card', Card);
Vue.component('Checkbox', Checkbox);
Vue.component('Column', Column);
Vue.component('DataTable', DataTable);
Vue.component('DataView', DataView);
Vue.component('Dialog', Dialog);
Vue.component('Dropdown', Dropdown);
Vue.component('InputMask',InputMask);
Vue.component('InputNumber',InputNumber);
Vue.component('InputText',InputText);
Vue.component('Listbox',Listbox);
Vue.component('Message',Message);
Vue.component('Panel',Panel);
Vue.component('Password',Password);
Vue.component('ProgressBar',ProgressBar);
Vue.component('RadioButton',RadioButton);
Vue.component('Textarea',Textarea);
Vue.component('Toolbar', Toolbar);